# Same as production but uses the .env.dev file instead.
FROM node:18-alpine

# Install required dependencies
RUN apk add --no-cache \
    bash \
    git \
    build-base \
    postgresql-client \
    ca-certificates \
    openssl \
    curl

ENV WORK /opt/jore
WORKDIR ${WORK}

# Install app dependencies
COPY package.json yarn.lock ./
COPY .env.dev ${WORK}/.env

RUN yarn install --frozen-lockfile

# Copy app source
COPY . .

CMD ["yarn", "run", "start:production"]
