# Same as production but uses the .env.dev file instead.

FROM node:18

RUN apt-get update && \
  apt-get -y install git build-essential software-properties-common && \
  # Needs new versions from the Buster repo, otherwise the matcher won't work
  apt-add-repository 'deb http://ftp.us.debian.org/debian buster main contrib non-free' && \
  apt-get update && \
  apt-get -y install postgresql-client-11 && rm -rf /var/lib/apt/lists/*

ENV WORK /opt/jore

WORKDIR ${WORK}
# Install app dependencies
COPY package.json ${WORK}
COPY yarn.lock ${WORK}

# Copy the env file for production
COPY .env.dev ${WORK}/.env

RUN yarn install

# Copy app source
COPY . ${WORK}
CMD yarn run start:production
