name: Build and publish Docker Hub dev image

on: [push, pull_request]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
      - name: Build dev and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: hsldevcom/jore-history-graphql-import
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          tags: dev
